spring.application.name=projectY

# DB
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/jobhunter
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

#JWT
projectY.jwt.base64-secret=jFxUtetk30VwU+vOoF+Ni7xMgWRwNDullT2m9atFT5yEhsVwlFUKIAiWm55T2xGrdB4SGYuZ+S1ddGgeJS6yWw==
# NEVER expr
projectY.jwt.access-token-validity-in-seconds=8640000
projectY.jwt.refresh-token-validity-in-seconds=8640000

#Pagination
spring.data.web.pageable.one-indexed-parameters=true

#Upload path
projectY.upload.base-URI=file:///media/ducnv/DU%20LIEU/learn_java/upload/

#Upload config
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
